IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'category')
BEGIN
    CREATE TABLE category (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        ATTRIBUTE VARCHAR(255) NOT NULL,
        PARENT_CATEGORY_ID INT,
        FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES category(ID)
    );
END
