IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'store')
BEGIN
    CREATE TABLE store (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME TEXT NOT NULL,
        LOGO VARCHAR(255) NOT NULL,
        HOME_IMAGE VARCHAR(255) NOT NULL,
        DEALS_IMAGE VARCHAR(255) NOT NULL,
        DEALS_SQUARE_IMAGE VARCHAR(255) NOT NULL,
        INTERACTIVE_IMAGE VARCHAR(255) NOT NULL,
        SELLER_ID INT,
        FOREIGN KEY (SELLER_ID) REFERENCES seller(ID)
    );
END
