-- V1_08__Create_Variant_Table.sql
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'variant')
BEGIN
    CREATE TABLE variant
    (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME VARCHAR(255),
        SKU_CODE VARCHAR(255),
        STOCK_QUANTITY INT,
        WEIGHT FLOAT,
        PRICE FLOAT,
        SALE_PRICE FLOAT,
        IMG VARCHAR(255),
        IS_DELETED BIT DEFAULT 0,
        PRODUCT_ID INT,
        FOREIGN KEY (PRODUCT_ID) REFERENCES product (ID)
    );
END
