IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'store_category')
BEGIN
    CREATE TABLE store_category (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        HERO_IMAGE VARCHAR(500) NOT NULL,
        SQUARE_IMAGE VARCHAR(500) NOT NULL,
        PARENT_STORE_CATEGORY_ID INT,
        STORE_ID INT,
        FOREIGN KEY (PARENT_STORE_CATEGORY_ID) REFERENCES store_category(ID),
        FOREIGN KEY (STORE_ID) REFERENCES store(ID)
    );
END
