IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'option_table')
BEGIN
    CREATE TABLE option_table (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME VARCHAR(255),
        PRODUCT_ID INT,
        FOREIGN KEY (PRODUCT_ID) REFERENCES product(ID)
    );
END
