IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'hashtag')
BEGIN
    CREATE TABLE hashtag (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME VARCHAR(50) NOT NULL,
        PRODUCT_ID INT NOT NULL,
        FOREIGN KEY (PRODUCT_ID) REFERENCES product(ID)
    );
END
