IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'variant_optionvalue')
BEGIN
    CREATE TABLE variant_optionvalue (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        VARIANT_ID INT,
        OPTIONVALUE_ID INT,
        FOREIGN KEY (VARIANT_ID) REFERENCES variant (ID),
        FOREIGN KEY (OPTIONVALUE_ID) REFERENCES optionvalue (ID)
    );
END
