IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'productattribute')
BEGIN
    CREATE TABLE productattribute (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        NAME VARCHAR(255),
        VALUE VARCHAR(255),
        PRODUCT_ID INT,
        FOREIGN KEY (PRODUCT_ID) REFERENCES product(ID)
    );
END
