IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'comment')
BEGIN
    CREATE TABLE comment (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        CONTENT TEXT NOT NULL,
        REVIEW_ID INT NOT NULL,
        SELLER_ID INT NOT NULL,
        FOREIGN KEY (REVIEW_ID) REFERENCES review(ID),
        FOREIGN KEY (SELLER_ID) REFERENCES seller(ID)
    );
END
