IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'video')
BEGIN
    CREATE TABLE video (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        VIDEO_PATH VARCHAR(255),
        VARIANT_ID INT,
        STORE_CATEGORY_ID INT,
        FOREIGN KEY (VARIANT_ID) REFERENCES variant (ID),
        FOREIGN KEY (STORE_CATEGORY_ID) REFERENCES store_category (ID)
    );
END
