IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'verification_token')
BEGIN
    CREATE TABLE verification_token (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        TOKEN VARCHAR(200),
        EXPIRY_DATE DATE,
        USER_ID INT UNIQUE,
        FOREIGN KEY (USER_ID) REFERENCES [user] (ID)
    );
END
