IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'payment_method')
BEGIN
    CREATE TABLE payment_method (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        USER_ID INT,
        CART_NUMBER INT,
        NAME_ON_CARD VARCHAR(255),
        EXPIRATION_DATE VARCHAR(255),
        DEFAULT_PAYMENT BIT DEFAULT 0,
        FOREIGN KEY (USER_ID) REFERENCES [user](ID)
    );
END
