IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'save_for_later')
BEGIN
    CREATE TABLE save_for_later (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        QUANTITY INT NOT NULL CHECK (QUANTITY >= 0),
        CART_ID INT,
        VARIANT_ID INT,
        FOREIGN KEY (CART_ID) REFERENCES cart (ID),
        FOREIGN KEY (VARIANT_ID) REFERENCES variant (ID)
    );
END
