IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'optionvalue')
BEGIN
    CREATE TABLE optionvalue (
        ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
        VALUE VARCHAR(255),
        OPTION_ID INT,
        FOREIGN KEY (OPTION_ID) REFERENCES option_table(ID)
    );
END
