IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'review')
BEGIN
    CREATE TABLE review
    (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        STAR INT NOT NULL,
        TITLE VARCHAR(255) NOT NULL,
        CONTENT VARCHAR(MAX) NOT NULL,
        IMAGE01 VARCHAR(255),
        IMAGE02 VARCHAR(255),
        IMAGE03 VARCHAR(255),
        IMAGE04 VARCHAR(255),
        IMAGE05 VARCHAR(255),
        VIDEO VARCHAR(255),
        VERIFIED_SHOP BIT DEFAULT 1,
        VERIFIED_ADMIN BIT DEFAULT 1,
        CREATED_AT DATETIME,
        UPDATED_AT DATETIME,
        CUSTOMER_ID INT,
        VARIANT_ID INT NOT NULL,
        FOREIGN KEY (CUSTOMER_ID) REFERENCES [user](ID),
        FOREIGN KEY (VARIANT_ID) REFERENCES variant(ID)
    );
END
